default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: jamify_development
  host: localhost
test:
  <<: *default
  database: jamify_test
  host: localhost
production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>