default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
development:
  <<: *default
  database: defalt
  host: localhost
test:
  <<: *default
  database: default
  host: localhost
production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>